import Navbar from "@/components/Navbar";

export const metadata = {
    title: 'Watcher Movies',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='pt-br'>
            <body className="bg-slate-800">
                <Navbar className='fixed top-0 left-0 bg-slate-950 w-full h-[60px] shadow-md overflow-auto'/>
                <main className="mt-[80px]">
                    {children}
                </main>
            </body>
        </html>
    );
}
